### ISSUE TITLE
Add CS Fixer

### ISSUE THREAD

**Issue by leovujanic** [NullTraining/project-team3#138]
For maintainers to have same code style standards add and configure CS Fixer

**Comment by msvrtan** [comment]
Installation

```
composer req --dev friendsofphp/php-cs-fixer
```

For configuration feel free to use `https://github.com/NullTraining/project-team1/blob/master/.php_cs.dist`

Running it on CircleCI `https://github.com/NullTraining/project-team1/blob/master/circle.yml#L50`
