### ISSUE TITLE
Create migrations for existing entities

### ISSUE THREAD

**Issue by msvrtan** [NullTraining/project-team3#42]
In order to start using migrations,
We need to create them for existing entities

Each entity should have it's own migration

Steps:

1) Drop current database
2) Create database
3) Run migration diff and remove all but 1 entity
4) Run migrations
5) Repeat step 3 & 4 until each entity is in

**Comment by leovujanic** [comment]
@msvrtan how do you mean "Run migration diff and remove all but 1 entity"? Do I need generate all migrations and then delete generated?
