### ISSUE TITLE
Integrate FOSUserBundle with easy admin

### ISSUE THREAD

**Issue by div3r** [NullTraining/project-team3#82]
For admin to manage users it would be nice to integrating FOSUserBundle with easy admin bundle
https://symfony.com/doc/current/bundles/EasyAdminBundle/integration/fosuserbundle.html

**Comment by div3r** [comment]
As easy admin is installed, just run php bin/console doctrine:fixtures:load to put predefined values to user tables.

**Comment by leovujanic** [comment]
@div3r can we close this?
